### ISSUE TITLE
November 21, 2013 Special General Election Results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-tn#17]
Parse PDFs into [county-level](http://sos-tn-gov-files.s3.amazonaws.com/TNH91GeneralTotals.pdf) and [precinct-level](http://sos-tn-gov-files.s3.amazonaws.com/TNH91GeneralPrecinct.pdf) files. Filenames will be:

* `20131121__tn__special__general__county.csv` (headers: `county`, `office`, `district`, `party`, `candidate`, `votes`)
* `20131121__tn__special__general__precinct.csv` (headers: `county`, `precinct`, `office`, `district`, `party`, `candidate`, `votes`)

**Comment by kindofluke** [comment]
I just submitted a PR #19 for this issue. let me know. I ended up doing it by hand because it was short and tabula didn't parse the file.
