### ISSUE TITLE
Parse March 2011 Special Election results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-tn#3]
Using these [county](http://tn.gov/sos/election/results/2011/20110308StateCertCountyTotals.pdf) and [precinct](http://tn.gov/sos/election/results/2011/20110308StateCertPrecinctTotals.pdf) files, along withTabula or xPDF, produce both county and precinct files for state legislative races. Header row is:

`county`, `precinct`, `office`, `district`, `party`, `candidate`, `votes`

`district` should be 6 for all rows, and `precinct` blank for county-level file.

- [ ] `20110308__tn__special__general.csv` (county)
- [ ] `20110308__tn__special__general__precinct.csv` (precinct)

**Comment by danhillreports** [comment]
@dwillis `district` should be 18 for all rows, not 6, right?

**Comment by dwillis** [comment]
Yes, my mistake. Good catch!
